object_recognition_msgs/RecognizedObjectArray objectarray
string filter
sensor_msgs/Image image
---
geometry_msgs/PoseWithCovarianceStamped selected_object_pose
sensor_msgs/Image seg_image
string workspace
